# Generated by Django 4.2 on 2023-04-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='videos/%y')),
                ('description', models.TextField(default='')),
            ],
        ),
    ]
