# Generated by Django 4.2 on 2023-04-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview',
            field=models.ImageField(default='default_preview.jpg', upload_to='images'),
        ),
    ]
