# Generated by Django 4.2 on 2023-04-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0004_alter_video_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='preview',
            field=models.ImageField(default='/default_preview.jpg', upload_to='images/%y'),
        ),
    ]
