# Generated by Django 4.2 on 2023-04-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
